### PR TITLE
 Hussain zawad

### PR DESCRIPTION
**Pull request by hussain-alzawad**

### CODE REVIEW

**Comment by ThekraSul** [comment]
Hussain, you got 4.5/5 in Logistic Regression Lab.

**Comment by hussain-alzawad** [comment]
Hello ,

Please explain what did i do wrong ?

Thanks,
hussain

________________________________

**Comment by ThekraSul** [comment]
Hello Hussain,

I wanted to bring to your attention that I noticed your assignment wasn't submitted by the deadline specified.

Wish you all the best🙏🏻

**Comment by hussain-alzawad** [comment]
Hello,

The assignment was on a Sunday or a Tuesday and I explained my situation to Hamad.
Please confirm with him regarding assignments on Sunday and Tuesday.
On these days I go back and forth between Riyadh and Dhahran making it impossible to solve before the deadline.

Thanks,
Hussain
________________________________

**Pull request closed without merging**
